### PR TITLE
Fixes and QoL improvements for Linux Usage

### PR DESCRIPTION
**Pull request by RickyGrassmuck**
### Fix issue preventing avr-size from running on Linux

There is a bug in the patch that adds the `--format=avr` flag in the
avr-size command that leads to the command failing. This PR switches to using the
short flag (`-A`) for the avr output format as a work around.

The bug already has an open bug report but change made here will still work after
the fix has been implemented so there won't be a need to change going forward.

### Streamline Flashing/building on Linux
    
- Renamed the Unix scripts to remove the '!' character which must be escaped when calling it from the command line.
- Made the build/clean/flash unix scripts executable to allow them to be executed directly

- Added prompt for the device path to look for when attempting to flash
- Wait for the specified device to be connected before attempting to flash
- Switch from using dfu-programmer to avrdude for flashing as it seems to be the more
  flexible tool.

### Testing

Below is the output from running the `00-FlashUnix.sh` script without pre-building the binary to show each step of the process working as expected. 

Note: You can see near the end the script begins printing `Device not found, retrying in 1 second...`. This is when you will need to connect your board and put it into programming mode 

_**Test below performed using an Inland Pro Micro ATMEGA32U4 ($6 USD from Microcenter)**_

```
[rigrassm@localhost DeviceSource]$ ./00-FlashUnix.sh   
Please select your board type by either number or name:
1 - at90usb1286  (for Teensy 2.0++)
2 - atmega16u2   (for Arduino UNO R3)
3 - atmega32u4   (for Arduino Micro, and Teensy 2.0)
Enter your board type: 3
Please enter the name of the program (without .hex): DaySkipperUS
Please enter the path to your devicd (ex. /dev/ttyACM0): /dev/ttyACM0
It looks like there is no hex file for DaySkipperUS.c
Would you like to build it now and then flash it? [y/n]y
 [INFO]    : Begin compilation of project "DaySkipperUS"...

avr-gcc (Fedora 10.2.0-1.fc33) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[ TRUNCATED COMPILER OUTPUT]

 [LNK]     : Linking object files into "DaySkipperUS.elf"
avr-gcc obj/DaySkipperUS.o obj/HIDParser.o obj/Device_AVR8.o obj/EndpointStream_AVR8.o obj/Endpoint_AVR8.o obj/Host_AVR8.o obj/PipeStream_AVR8.o obj/Pipe_AVR8.o obj/USBController_AVR8.o obj/USBInterrupt_AVR8.o obj/ConfigDescriptors.o obj/DeviceStandardReq.o obj/Events.o obj/HostStandardReq.o obj/USBTask.o obj/FrameworkSettings.o obj/DeviceSettings.o obj/HardwareLED.o obj/PokemonSettings.o -o DaySkipperUS.elf -lm -Wl,-Map=DaySkipperUS.map,--cref -Wl,--gc-sections -Wl,--relax -mmcu=atmega32u4 obj/obj-atmega32u4/CRC32.o obj/obj-atmega32u4/uart.o obj/obj-atmega32u4/HardwareUSB.o obj/obj-atmega32u4/HardwareSerial.o obj/obj-atmega32u4/SwitchController.o obj/obj-atmega32u4/PushButtons.o obj/obj-atmega32u4/SwitchButtons.o obj/obj-atmega32u4/CodeEntry.o obj/obj-atmega32u4/PokemonRoutines.o obj/obj-atmega32u4/DaySkipperUS_Core.o -lm
 [OBJCPY]  : Extracting HEX file data from "DaySkipperUS.elf"
avr-objcopy -O ihex -R .eeprom -R .fuse -R .lock -R .signature DaySkipperUS.elf DaySkipperUS.hex
 [OBJCPY]  : Extracting EEP file data from "DaySkipperUS.elf"
avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom="alloc,load" --change-section-lma .eeprom=0 --no-change-warnings DaySkipperUS.elf DaySkipperUS.eep || exit 0
 [OBJCPY]  : Extracting BIN file data from "DaySkipperUS.elf"
avr-objcopy -O binary -R .eeprom -R .fuse -R .lock -R .signature DaySkipperUS.elf DaySkipperUS.bin
 [OBJDMP]  : Extracting LSS file data from "DaySkipperUS.elf"
avr-objdump -h -d -S -z DaySkipperUS.elf > DaySkipperUS.lss
 [NM]      : Extracting SYM file data from "DaySkipperUS.elf"
avr-nm -n DaySkipperUS.elf > DaySkipperUS.sym
 [SIZE]    : Determining size of "DaySkipperUS.elf"

avr-size --mcu=atmega32u4 -A DaySkipperUS.elf
DaySkipperUS.elf  :
section                      size      addr
.data                          30   8388864
.text                        9758         0
.bss                          237   8388894
.stab                        1068         0
.stabstr                      189         0
.comment                       35         0
.note.gnu.avr.deviceinfo       64         0
.debug_aranges               1640         0
.debug_pubnames              1901         0
.debug_info                 33572         0
.debug_abbrev               10190         0
.debug_line                 34664         0
.debug_frame                 3476         0
.debug_str                   9958         0
.debug_loc                  21531         0
.debug_ranges                2264         0
Total                      130577


 [INFO]    : Finished building project "DaySkipperUS".
Device not found, retrying in 1 second...
Device not found, retrying in 1 second...
Device not found, retrying in 1 second...
Device not found, retrying in 1 second...
Device not found, retrying in 1 second...
Device not found, retrying in 1 second...
Device not found, retrying in 1 second...
Device not found, retrying in 1 second...
Flashing DaySkipperUS.hex to atmega32u4 now

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9587 (probably m32u4)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "DaySkipperUS.hex"
avrdude: input file DaySkipperUS.hex auto detected as Intel Hex
avrdude: writing flash (9788 bytes):

Writing | ################################################## | 100% 0.73s

avrdude: 9788 bytes of flash written
avrdude: verifying flash memory against DaySkipperUS.hex:
avrdude: load data flash data from input file DaySkipperUS.hex:
avrdude: input file DaySkipperUS.hex auto detected as Intel Hex
avrdude: input file DaySkipperUS.hex contains 9788 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.07s

avrdude: verifying ...
avrdude: 9788 bytes of flash verified

avrdude: safemode: Fuses OK (E:CB, H:D8, L:FF)

avrdude done.  Thank you.

Finished flashing DaySkipperUS.hex to atmega32u4! 


```

### CODE REVIEW

**Comment by denvoros** [comment]
These are some great improvements for sure.

I would like to point out that removing `dfu-programmer` is going to affect all of the R3 users on Mac at least somewhat.

Initially these "Unix" scripts were built to try and support both Mac and Linux and the flashing was supposed to be for R3 boards alone, but if `avrdude` can flash all devices, then we'll need to adjust the manual and take into account how to instruct people to find the `/dev/tty` path of their board when they plug it in on Mac and Linux.

Perhaps we could have a switch statement for if the board was selected to be for the R3 so that it could continue to use `dfu-programmer`?

**Comment by RickyGrassmuck** [comment]
> These are some great improvements for sure.
> 
> I would like to point out that removing `dfu-programmer` is going to affect all of the R3 users on Mac at least somewhat.
> 
> Initially these "Unix" scripts were built to try and support both Mac and Linux and the flashing was supposed to be for R3 boards alone, but if `avrdude` can flash all devices, then we'll need to adjust the manual and take into account how to instruct people to find the `/dev/tty` path of their board when they plug it in on Mac and Linux.

Given how different the requirements and process is for flashing these boards on Mac and Linux, i'm 
> Perhaps we could have a switch statement for if the board was selected to be for the R3 so that it could continue to use `dfu-programmer`?



> These are some great improvements for sure.
> 
> I would like to point out that removing `dfu-programmer` is going to affect all of the R3 users on Mac at least somewhat.
> 
> Initially these "Unix" scripts were built to try and support both Mac and Linux and the flashing was supposed to be for R3 boards alone, but if `avrdude` can flash all devices, then we'll need to adjust the manual and take into account how to instruct people to find the `/dev/tty` path of their board when they plug it in on Mac and Linux.
> 
> Perhaps we could have a switch statement for if the board was selected to be for the R3 so that it could continue to use `dfu-programmer`?

So after thinking about it I decided to play around with auto-detecting the device on both mac and linux to address the concerns about having to teach people to locate their device paths. 

I just pushed a commit that adds this functionality and have tested it on both Linux and Mac (Catalina, work laptop doesn't have Big Sur yet thank all that is holy) and it works fantastically!

```
└──╼ $ ./00-FlashUnix.sh
Please select your board type by either number or name:
1 - at90usb1286  (for Teensy 2.0++)
2 - atmega16u2   (for Arduino UNO R3)
3 - atmega32u4   (for Arduino Micro, and Teensy 2.0)
Enter your board type: 3
Please enter the name of the program (without .hex): BallThrower
Would you like to attempt auto detecting your device? [y/n]: y
It looks like there is no hex file for BallThrower.c
Would you like to build it now and then flash it? [y/n]y
 [INFO]    : Begin compilation of project "BallThrower"...

 [INFO]    : Finished building project "BallThrower".
Waiting for device to connect...
Waiting for device to connect...
Waiting for device to connect...
Waiting for device to connect...
Device connected at [/dev/tty.usbmodem143101]
Attempting to flash BallThrower.hex to atmega32u4 now

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

[TRUNCATED]

avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.06s

avrdude: verifying ...
avrdude: 7890 bytes of flash verified

avrdude: safemode: Fuses OK (E:CB, H:D8, L:FF)

avrdude done.  Thank you.

Finished flashing BallThrower.hex to atmega32u4!
```

I'll work on adding a switch to revert to using dfu-programmer for the uno until i'm able to go grab one to test out using avrdude(from what i'm reading it should work but I can't verify that).

**Comment by RickyGrassmuck** [comment]
Lots of changes in the last commit. Main thing being adding back the dfu-programmer option.

The 00-FlashUnix.sh script has been completely overhauled making it a bit easier to read/follow as well as providing much improved output (pretty colors and all!). This commit should make the script work as it did previously for those relying on dfu-programmer so it should be fairly safe to merge without worrying about breaking peoples workflows.

That said, I do not have an UNO R3 to test with so I'd still suggest having someone that has one and a Mac give the script a run and make sure everything is on the up and up.

**Comment by Mysticial** [comment]
Is there a better alternative to `-A` that still lists the sizes?

This sort of information is actually fairly important to the devs to gauge how close we are to the limits:
```
Device: atmega16u2

Program:   11670 bytes (71.2% Full)
(.text + .data + .bootloader)

Data:        346 bytes (67.6% Full)
(.data + .bss + .noinit)
```
With `-A` we get this which slightly harder to parse.
```
avr-size --mcu=atmega16u2 -A AutoHost-MultiGame.elf
AutoHost-MultiGame.elf  :
section             size      addr
.data                120   8388864
.text              11550         0
.bss                 226   8388984
.debug_aranges      1976         0
.debug_pubnames     5293         0
.debug_info        34889         0
.debug_abbrev       9180         0
.debug_line        27654         0
.debug_frame        3248         0
.debug_str         12232         0
.debug_loc         20445         0
.debug_ranges       2152         0
Total             128965
```
If there's no alternative, I can still live with this.

**Comment by rigrassm** [comment]
Looks like `-C` Gives the output from your first command. I'll switch it and push it up

**Comment by RickyGrassmuck** [comment]
@Mysticial I made mental error, I actually meant to use `-C` which is the short flag for the `--format=avr` long option.

Made the change and pushed.

**Comment by Mysticial** [comment]
Nice! Thanks!

So cases that are touched are:
- Mac: Uno
- Mac: Teensy (tested ok)
- Linux: Uno
- Linux: Teensy (tested ok)

Two cases left right?

**Comment by RickyGrassmuck** [comment]
Yup.

I did simulate building/flashing with dfu-programmer for the UNO arch and
it ran exactly the same as the old script (flashing fails since I don't
have an actual UNO connected) so as long as what we had was working before
it will continue working.

If I end up in the area tomorrow, I may snatch an UNO from Microcenter to
test things out with.

**Comment by RickyGrassmuck** [comment]
Just grabbed me an uno to play around with so I'll be testing this out when I get home in about 45 minutes

**Comment by RickyGrassmuck** [comment]
I lied yesterday. Didn't get to play with the uno after grabbing it since I forgot to get a USB A to B cable lol. Plan on picking one up today though

**Comment by Mysticial** [comment]
No worries! Let us know when this is ready. We're getting close to another release so we want to pick this up before everything gets overwritten on the next snapshot dump.

**Comment by RickyGrassmuck** [comment]
Grabbed the USB cable earlier tonight so I'll give it a go tomorrow!

**Comment by RickyGrassmuck** [comment]
Good news, Mac+UNO confirmed working! Cleaned up the prompt and it's now ready to go!

```
└──╼ $ ./00-FlashUnix.sh

=================================
Configuration
=================================

** Using sudo for flashing device, you may need to provide your password!
Please select your board type by either number or name:
1 - at90usb1286  (for Teensy 2.0++)
2 - atmega16u2   (for Arduino UNO R3)
3 - atmega32u4   (for Arduino Micro, and Teensy 2.0)

Enter your board type:
2

Please enter the name of the program (without .hex):
BallThrower

Mac platform detected, UNO R3 configured. Connect your device and enter DFU mode, then press any key...:


=================================
Flashing BallThrower.hex ...
=================================

Checking memory from 0x0 to 0x2FFF...  Not blank at 0x1.
Erasing flash...  Success
Checking memory from 0x0 to 0x1AFF...  Empty.
0%                            100%  Programming 0x1B00 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
0%                            100%  Reading 0x3000 bytes...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  Success
Validating...  Success
0x1B00 bytes written into 0x3000 bytes memory (56.25%).

=================================
Finished flashing BallThrower.hex to atmega16u2!
=================================
```

**Pull request merged**
